### ISSUE TITLE
create prototype for visualization for KC

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/connect#105]
Use case: As a **person responsible for overseeing supervisions** I want to **see which LGAs are performing best, and which are underperforming** so that I can know where to channel resources / interventions in order to improve performance. 

This visualisation should be within Kano Connect. Kano Connect has existing tabs: 

* Home
* Directory
* Health Facilities 
* Reports 
* Calendar 

Question: I'm assuming this is an important function, therefore, should appear in navigation. Do we think this is a 'report', [therefore should be embedded within the report tab] OR a separate thing [therefore a head level item]?

**Comment by danse** [comment]
We built a prototypical visualisation, currently accessible here http://demo.ehealthafrica.org/kano/. It is not integrated in Kano Connect yet, and it will probably never be because we have been told by Kathleen that a visualisation is not requested. What is requested is a system of alerts, along with the necessary data cleaning
