### ISSUE TITLE
Add alerts round which are currently blocked

### ISSUE THREAD

**Issue by lucychambers** [eHealthAfrica/connect#145]
See ones in [this sheet](https://docs.google.com/spreadsheets/d/1pHs2FGXcNzihjsFY57nbd7HZdKeETRAUkPBFivTK6No/edit#gid=625816179) which are currently blocked. 

Awaiting information from Temitope.

**Comment by danse** [comment]
This is the detail of the info missing:

1) Proportion of visits

The following alerts seem to be of the same kind, and the only difference
among them is the level:

- Proportion of SS visits conducted by the state to the zones
- Number/percent of SS visits conducted by the zones to the LGAs
- Number/percent of SS visits conducted by the LGAs to HFs

Their benchmark value is 90% for every level. I assume that their
meaning is "Percentage of planned visits which was actually conducted",
so i can calculate the percentage using the fields: `conducted_ss` and
`planned_ss`. Just to be sure, can you confirm?

The fields `conducted_ss` and `planned_ss` seem to be missing for the
level with smallest grain, Local Government Areas -> Health
Facilities, corresponding to Formhub id `riss_checklist_nig_v4`. How
should we calculate the percentage in that case?

2) Retirements of funds

Which fields should i use to calculate "Number of Zones with timely
and complete retirements of RI funds for the preceding month of SS
visit"? This is an alert at the topmost level, States -> Zones

3) Microplans updated

Which fields should i use to calculate "Number of LGAs with microplans
updated last quarter"? This is an alert at the level Zones -> Local
Government Areas

4) Timely funds

"Number of HFs that received timely funds to conduct services in the
last 3 months" is an alert at the most specific level, Local
Government Areas -> Health Facilities, with benchmark set to 100%. I
think that the relevant field is `funding_ri`, but the values stored
there are `41` or `42`, while i would expect just yes/no values

**Comment by danse** [comment]
@lucychambers this is both not blocking for the milestone and unlikely to be ready by the end of next sprint, so i am removing it from the milestone

**Comment by danse** [comment]
> @lucyfedia: Now in response to your questions. The question about Timely funding.  Yes is coded 41 & No is coded 42

Temitope just answered on Slack

**Comment by danse** [comment]
Over the last days, and especially this morning after the meeting with the board, we have got all our answers:

1) The bottom level, "Local Government Areas -> Health Facilities", is different. For this level, areas should conduct *at least one* visit to *every* health facility. Every visit will correspond to a submission of a form to the Formhub database corresponding to this level. This is the way to calculate this indicator _just for this level_, even though there are indicators with the same name also on other levels. Matching health facilities is a problem currently, but we were told that a new form, with a closed selection of health facility names will be rolled out by the 12 of June.

2) Timely retirement of funds is related to the binary field `ri_funds` in the relative form. _Complete_ retirement of funds means that all form submissions for a given zone well need to have a positive answer. There were still some internal discussion within the board members about the utility and definition of this alerts, but we now have the information needed in order to start calculating a first version for it.

3) The field about microplans is `ri_microplan`. This field is available just at the topmost level, State -> Zones, and the indicator should be moved to the topmost level

4) As mentioned also above, Temitope explained us that "Yes is coded 41 & No is coded 42"

@lucychambers, @janetbutts, or Temitope, feel free to comment in case i got anything wrong
